extends: airbnb-base
env:
  browser: true
rules:
  semi:
    - error
    - never
  arrow-parens:
    - error
    - as-needed
  import/prefer-default-export:
    - warning
    - always
  import/extensions:
    - warning
    - never
  import/no-absolute-path:
    - off
  import/no-unresolved:
    - warning
  no-unused-vars:
    - off
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
