export const types = {
  FILTER: 'FILTER',
  ADD_TASK: 'ADD_TASK',
  DELETE_TASK: 'DELETE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  TRIGGER_TASK: 'TRIGGER_TASK',
  NOTIFY: 'NOTIFY',
  SHOW_IMAGE: 'SHOW_IMAGE',
  CHANGE_IMAGE: 'CHANGE_IMAGE',
  SUBSTITUTE_ROUTE: 'SUBSTITUTE_ROUTE',
  CHANGE_INPUT: 'CHANGE_INPUT',
  INIT: 'INIT',
}

export const asyncTypes = {
  ADD_TASK: '@ADD_TASK',
  DELETE_TASK: '@DELETE_TASK',
  SAVE_TASKS: '@SAVE_TASKS',
  UPDATE_TASK: '@UPDATE_TASK',
  TRIGGER_TASK: '@TRIGGER_TASK',
  NOTIFY: '@NOTIFY',
  CHANGE_IMAGE: '@CHANGE_IMAGE',
  CHANGE_INPUT: '@CHANGE_INPUT',
  CLEAR_INPUT: '@CLEAR_INPUT',
  TOUCH_START: '@TOUCH_START',
}
