export const types = {
  INIT: 'INIT',
  FILTER: 'FILTER',
  CREATE_TASK: 'CREATE_TASK',
  ADD_TASK: 'ADD_TASK',
  DELETE_TASK: 'DELETE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  TRIGGER_TASK: 'TRIGGER_TASK',
  NOTIFY: 'NOTIFY',
  NOTIFICATION_SHOW: 'NOTIFICATION_SHOW',
  NOTIFICATION_HIDE: 'NOTIFICATION_HIDE',
  SHOW_IMAGE: 'SHOW_IMAGE',
  HIDE_IMAGE: 'HIDE_IMAGE',
  CHANGE_IMAGE: 'CHANGE_IMAGE',
  SUBSTITUTE_ROUTE: 'SUBSTITUTE_ROUTE',
  CHANGE_INPUT: 'CHANGE_INPUT',
  CLEAN_INPUT: 'CLEAN_INPUT',
  MOVE_TASK: 'MOVE_TASK',
  SHOW_INFO: 'SHOW_INFO',
}

// TODO: implement patching tasks on long press or smthg
